AWSTemplateFormatVersion: 2010-09-09
Description: App Isolated Dev bubble. After a new App VPC is attached to the TGW, handle the TGW RT configurations.

Parameters:
  NewAttachmentID:
    Type: String
    Description: The ID of the attachment
  NewAttachmentCIDRBlock:
    Type: String
    Description: The CIDRBlock of the VPC behind the attachment

Resources:
###############
# Association #
###############
  # Associate the App Isolated Dev route table to the new attachment
  AppIsolatedDevRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue AppIsolatedDevTGWRTID

################
# Propagations #
################
  # "Propagate" the CIDRblock on the Network route table
  NetworkTGWRouteTableRoutePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue NetworkTGWRTID
  # "Propagate" the CIDRblock on the Shared Service route table
  SharedServicesTGWRouteTableRoutePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue SharedServicesTGWRTID

###############
# Black holes #
###############
  # Blackhole the new App VPC attachment on the AppIsolated Dev Route Table
  AppIsolatedDevTGWRouteTableBlackholeRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      Blackhole: true
      DestinationCidrBlock: !Ref NewAttachmentCIDRBlock
      TransitGatewayRouteTableId: !ImportValue AppIsolatedDevTGWRTID
  # Blackhole the new App VPC attachment on the AppIsolated Prod Route Table
  AppIsolatedProdTGWRouteTableBlackholeRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      Blackhole: true
      DestinationCidrBlock: !Ref NewAttachmentCIDRBlock
      TransitGatewayRouteTableId: !ImportValue AppIsolatedProdTGWRTID
