AWSTemplateFormatVersion: 2010-09-09
Description: VPC creation template that just call the backend Custom Resource

Parameters:
  AppName:
    Type: String
    Description: The name that will be used to tag the newly created resources
  VPCCidr:
    Type: String
    Description: The CIDR of the new VPC, must be between /16 and /23 (because those are VPCs with 9 subnets)
    AllowedPattern: >-
      ^([0-9]|1?[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|1?[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|1?[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|1?[0-9]{2}|2[0-4][0-9]|25[0-5])\/(1[6-9]|2[0-3])$
  AccountID:
    Type: String
    Description: The AWS account ID in which we deploy the VPC. Current account if left empty
    AllowedPattern: >-
      ^([0-9]{12})?$
  Region:
    Type: String
    Description: The AWS region in which we deploy the new VPC (a Transit Gateway MUST already exist in this region). Current Region if left empty
    AllowedValues:
      - ''
      - af-south-1
      - ap-east-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-south-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - me-south-1
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
  NetworkBubble:
    Type: String
    Description: The Network "bubble" in which the new VPC will be placed. See doc.
    Default: shared-services
    AllowedValues:
      - app-isolated-dev
      - app-isolated-prod
      - shared-services
      - network
  ForceUpdateParameter:
    Type: String
    Description: This parameter is not used by the stack and its value is irrelevant, but changing it will force an update in case you need it

Conditions:
  UseCurrentAccount: !Equals [ !Ref AccountID, '' ]
  UseCurrentRegion: !Equals [ !Ref Region, '' ]

Resources:
  GlobalNetworkVPC:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !ImportValue CustomResourceNetworkManagement
      AppName: !Ref AppName
      VPCCidr: !Ref VPCCidr
      AccountID: !If [ UseCurrentAccount, !Ref 'AWS::AccountId', !Ref AccountID ]
      Region: !If [ UseCurrentRegion, !Ref 'AWS::Region', !Ref Region ]
      NetworkBubble: !Ref NetworkBubble
      ForceUpdateParameter: !Ref ForceUpdateParameter

Outputs: {}