AWSTemplateFormatVersion: 2010-09-09
Description: Shared Services bubble. After a new App VPC is attached to the TGW, handle the TGW RT configurations.

Parameters:
  NewAttachmentID:
    Type: String
    Description: The ID of the attachment
  NewAttachmentCIDRBlock:
    Type: String
    Description: The CIDRBlock of the VPC behind the attachment

Resources:
###############
# Association #
###############
  # Associate the Network route table to the new attachment
  SharedServiceRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue SharedServicesTGWRTID

################
# Propagations #
################
  # "Propagate" the CIDRblock on the Network route table
  NetworkTGWRouteTableRoutePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue NetworkTGWRTID
  # "Propagate" the CIDRblock on the Shared Service route table
  SharedServicesTGWRouteTableRoutePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue SharedServicesTGWRTID
  # "Propagate" the CIDRblock on the AppIsolated Prod route table
  AppIsolatedProdTGWRouteTableRoutePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue AppIsolatedProdTGWRTID
  # "Propagate" the CIDRblock on the AppIsolated Dev route table
  SAppIsolatedDevTGWRouteTableRoutePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref NewAttachmentID
      TransitGatewayRouteTableId: !ImportValue AppIsolatedDevTGWRTID

###############
# Black holes #
###############
  # None
